main:
  - name: নীড়
    url: /
    weight: 1
  - name: পরিচিতি
    url: /about/
    weight: 2
  - name: পোস্ট
    url: /posts/
    weight: 3
  - name: যোগাযোগ
    url: /contact/
    weight: 4
  - name: ট্যাগ
    url: /tags/
global: 
  - name: "জন্ম, মৃত্যু, বিবাহ ও সংশ্লিষ্ট পরিসেবা"
    params:
      label: বিস্তারিত দেখুন
  - name: "পেনশন, ভাতা ও অন্যান্য"
  - name: "ব্যবসায় ও বাণিজ্য"
  - name: "আইন, অপরাধ ও বিচার"
  - name: "জাতীয় পরিচয়পত্র ও নাগরিকত্ব"
  - name: "শিক্ষা ও বৃত্তি"
  - name: "গ্রাম ও কুটির শিল্প"
  - name: "নগর"
  - name: "সমাজ ও সংস্কৃতি"
  - name: "বাংলাদেশ"
  - name: "শ্রম ও কর্মসংস্থান"
  - name: "প্রবাস ও রেমিট্যান্স"
  - name: "অর্থ ও কর"
  - name: "গৃহায়ন ও স্থানীয় পরিসেবা"
  - name: "পাসপোর্ট, বৈদেশিক ভ্রমণ"
  - name: "ভিসা ও ইমিগ্রেশন"