
baseURL: "https://aishikrehman.com"
DefaultContentLanguage: "bn"
defaultContentLanguage: "bn"
defaultContentLanguageInSubdir: "false"
enableMissingTranslationPlaceholders: "false"

languages:
  bn:
    disabled: false
    contentDir: content/bn
    languageCode: bn-BD
    languageDirection: ltr
    languageName: বাংলা
    title: ঐশিক রেহমান
    weight: 1
    params:
      subtitle: উইকিমিডিয়ান, লেক্সিকোগ্রাফার
      author:
        name: ঐশিক রেহমান
    menu:
      main:
        - name: পরিচিতি
          url: /about/
        - name: পোস্ট
          url: /posts/
        - name: ট্যাগ
          url: /tags/
  en:
    disabled: false
    contentDir: content/en
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Aishik Rehman
    weight: 2
    params:
      subtitle: Wikimedian and Lexicolgist and CSEr.
      author:
        name: Aishik Rehman
    menu:
      main:
        - name: About
          url: /en/about/
        - name: Posts
          url: /en/posts/

paginate: 10
googleAnalytics: "G-3NFDT41J8E"

Params:
  author:
    name: Aishik Rehman
    jobtitle: Wikimedian and Lexicolgist and CSEr.
    url: "https://aishikrehman.com/about/bn/"
    email: hello@aishikrehman.com
    locality: Mymensingh, Bangladesh
    social: 
      facebook: "https://facebook.com/aishikrehman"
      linkedin: "https://linkedin.com/in/aishikrehman"
      youtube: "https://youtube.com/@aishikrehman"
      github:  "https://github.com/aishikrehman"
      wikipedia: "https://bn.wikipedia.com/wiki/User:Aishik Rehman"
    twitter: RehmanAishik 
    phone: "+880 1601 6606 66"
    url: https://aishikrehman.com/about/
    picture: /assets/images/Aishik Rehman_Mymensingh_2019.jpg
  github:
    user: aishikrehman
    repo: aishikrehman.github.io
    branch: main
  og:
    image: /assets/images/Aishik Rehman-og-image.png
  description: a Bengali computational linguist and developer with a background in computer science and engineering.

taxonomies:
  tag: tags


markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
      
outputs:
  home: [ "HTML", "RSS", "JSON"]