global: 
  - name: "বাংলা লার্নিং মডিউল"
    url: "/learn-bengali/"
    params:
      label: অবাংলাভাষীদের জন্য বাংলা শিক্ষণ সামগ্রী
  - name: "পরিষদ বাংলা অভিধান"
    url: "/parisad-bengali-dictionary/"
    params:
      label: বাংলা ভাষার সর্বাধুনিক, সর্ববৃহৎ ও সমৃদ্ধ বাংলা অভিধান
  - name: "পরিষদ লোকজ শব্দকোষ"
    url: #
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "পরিষদ সমার্থক শব্দকোষ"
    url: #
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "বাংলা প্রবাদ সংগ্রহ"
    url: #
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "বাঙালির যা যা"
    url: #
    params:
      label: বাঙালির ভাষা, প্রযুক্তি, সংস্কৃতি সমস্ত কিছু নিয়ে গ্রন্থ
  - name: "Discrete Mathematics in Bengali"
    url: "/discrete-mathematics/"
    params:
      label: বাঙালির ভাষা, প্রযুক্তি, সংস্কৃতি সমস্ত কিছু নিয়ে গ্রন্থ
globallinks:
  - name: "ঐশিক আইটি সেন্টার"
    url: "https://itc.aishikrehman.com/"
    params:
      label: লক্ষীগঞ্জ বাজার, ঈশ্বরগঞ্জ, ময়মনসিংহ
  - name: "ঐশিক লার্নিং সেন্টার"
    url: "https://learn.aishikrehman.com/"
    params:
      label: লক্ষীগঞ্জ বাজার, ঈশ্বরগঞ্জ, ময়মনসিংহ
  - name: "বাংলা পরিষদ"
    url: "https://bengalicouncil.github.io/"