baseURL = "https://books.zerodemy.com"
languageCode = "bn-BD"
DefaultContentLanguage = "bn"
defaultContentLanguage = "bn"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

title = "Zerodemy Books"
paginate = 10
theme = "0demy"

[params]
  orgName = "ZeroDemy"
  siteSubTitle = "Collection of Bengali Books"
  siteSubTitleBN = "বাংলা বইয়ের সংগ্রহশালা"
  mainURL = "https://zerodemy.com/"
  siteURL = "https://books.zerodemy.com/"
  siteName = "জিরোডেমি বই"
  siteNames = [ "জিরোডেমি বই", "ZeroBooks", "0dmey Books" ]
  siteLang = "bn-BD"
  siteLogo = "https://zerodemy.com/dist/img/logo%20temporary.png"
  searchText = "বই খুঁজুন"
  gsc = "https://cse.google.com/cse.js?cx=a3eaf405be35e4a4b"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
      
[taxonomies]
  genre = 'genres'

[outputs]
  home = [ "HTML", "RSS", "JSON"]